<h1>infos de connexion</h1>
<form method="POST" action="">

    <fieldset>
        <p>
            <label for="email">Votre Email</label>
            <input type="email" name="email" id="email" required placeholder="email ..@....">
        </p>
        <p>
            <label for="mdp">Votre mot de passe</label>
            <input type="password" name="password" id="mdp" required placeholder="mot de passe">
        </p>
    </fieldset>

    <input type="submit" value="Se connecter" />
</form>
