<!-- Affichage du template lié à la vue -->
<h2><i class="fa fa-shopping-cart"></i> Passer une commande</h2>

<form data-order-step="run" id="order-form" class="generic-form ">

    <!-- Champ caché stockant le prix de vente du produit alimentaire sélectionné -->
    <input type="hidden" name="salePrice">

    <fieldset>
        <legend>Ajouter un article</legend>
        <ul>
            <li>
                <label for="meal">Nom :</label>
                <select id="meal" name="meal">
                    <?php foreach($meals as $meal) : ?>
                        <option value="<?= $meal['Id']; ?>"><?= $meal['Name']; ?></option>
                    <?php endforeach; ?>
                </select>
                <article id="meal-details" class="meal-details no-left-label">
                    <img src="" alt="Photo du produit" id="pic">
                    <p id="description"><?= $meals[0]['Description']; ?></p>
                    <span id="price">Prix : <strong><?= $meals[0]['SalePrice']; ?></strong></span>
                </article>
            </li>
            <li>
                <label for="quantity">Quantité :</label>
                <input id="quantity" class="quantity" value="1" type="text" maxlength="2" name="quantity" data-name="Quantité" data-type="positive-integer" data-required>
            </li>
            <li>
                <button id="add_basket" class="button button-primary no-left-label" type="button">Ajouter</button>
            </li>
        </ul>
    </fieldset>

</form>
<div id="basket"></div>


